version: '3.6'

services:
  my_app:
    image: exercise4/itsecouath2:1.0.0
    container_name: my_app
    environment:
      QUARKUS_OAUTH2_INTROSPECTION_URL: http://keycloak:8080/realms/myrealm/protocol/openid-connect/token/introspect
      QUARKUS_OAUTH2_ROLE_CLAIM: roles
    ports:
      - 8081:8081
    depends_on:
      keycloak:
        condition: service_healthy
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    command: start-dev --import-realm
    ports:
      - 8080:8080
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 30

